/**
 * Created by Алексей on 09.07.2017.
 */

export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU';
export const CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const TOGGLE_ITEMS_SELECT_MENU = 'TOGGLE_ITEMS_SELECT_MENU';
export const CLOSE_ITEMS_SELECT_MENU = 'CLOSE_ITEMS_SELECT_MENU';